
// ===== Mobile menu =====
(function(){var b=document.getElementById('menuBtn'),m=document.getElementById('mobileMenu');if(b&&m){b.addEventListener('click',function(){m.classList.toggle('hidden');});document.querySelectorAll('[data-close-mobile]').forEach(function(a){a.addEventListener('click',function(){m.classList.add('hidden');});});}})();
// ===== AdSense: push every ad unit on the page =====
window.addEventListener('load',function(){try{document.querySelectorAll('ins.adsbygoogle').forEach(function(){(window.adsbygoogle=window.adsbygoogle||[]).push({});});}catch(e){}});
// ===== Reading progress bar (article pages) =====
(function(){var bar=document.getElementById('progressBar');if(!bar)return;function upd(){var h=document.documentElement;var st=h.scrollTop||document.body.scrollTop;var sh=(h.scrollHeight||document.body.scrollHeight)-h.clientHeight;bar.style.width=(sh>0?(st/sh*100):0)+'%';}window.addEventListener('scroll',upd);upd();})();
// ===== Copy link =====
(function(){var c=document.getElementById('copyLink');if(!c)return;c.addEventListener('click',function(e){e.preventDefault();navigator.clipboard.writeText(window.location.href).then(function(){var t=c.innerHTML;c.innerHTML='<i class="fas fa-check"></i>';setTimeout(function(){c.innerHTML=t;},1500);});});})();
// ===== Article image fallback =====
document.querySelectorAll('img[data-fb]').forEach(function(im){im.addEventListener('error',function(){this.onerror=null;this.src='https://placehold.co/1200x630/ab183d/ffffff?text=Pro+CSC+Tools';});});
// ===== Blog posts (add a new object on top to publish a new article) =====
const blogPosts=[
  {title:"How to Use the QR Code Generator Tool (Step-by-Step)",excerpt:"Create URL, UPI, text, phone and Wi-Fi QR codes in seconds and download them in high quality - a complete beginner guide for CSC VLEs.",img:"/images/qr.webp",date:"Jun 28, 2026",tag:"Tutorial",url:"/blog/how-to-use-qr-Generator-tool.html",live:true},
  {title:"How to Make a Passport Size Photo Online",excerpt:"Create correct passport-size photos for forms and exams with the right dimensions, DPI and background - free.",img:"/images/passport.webp",date:"Coming soon",tag:"Guide",url:"#",live:false},
  {title:"How to Remove Photo Background for Free",excerpt:"Get a clean white or transparent background for ID photos and product images in one click.",img:"/images/bg.webp",date:"Coming soon",tag:"Guide",url:"#",live:false},
  {title:"How to Resize Photo & Signature for Exam Forms",excerpt:"Meet exact KB size and pixel limits for SSC, UPSC and other online application forms.",img:"/images/photo-sign.webp",date:"Coming soon",tag:"Tips",url:"#",live:false},
  {title:"How to Convert Images to PDF on Mobile",excerpt:"Combine multiple photos or documents into a single, share-ready PDF from your phone.",img:"/images/image-to-pdf.webp",date:"Coming soon",tag:"Guide",url:"#",live:false},
  {title:"How to Create GST Bills with the Invoice Generator",excerpt:"Make professional GST-ready invoices with auto totals and print-ready PDF for your shop.",img:"/images/invoice-generator.webp",date:"Coming soon",tag:"Tutorial",url:"#",live:false}
];
function blogInit(){
  var grid=document.getElementById('blogGrid');if(!grid)return;
  var featured=document.getElementById('featured');var catWrap=document.getElementById('catFilter');var empty=document.getElementById('blogEmpty');
  var active='All';var query='';
  var cats=['All'];blogPosts.forEach(function(p){if(cats.indexOf(p.tag)<0)cats.push(p.tag);});
  function fb(){grid.querySelectorAll('img[data-fb]').forEach(function(im){im.onerror=function(){this.onerror=null;this.src='https://placehold.co/600x300/ab183d/ffffff?text=Pro+CSC+Tools';};});if(featured)featured.querySelectorAll('img[data-fb]').forEach(function(im){im.onerror=function(){this.onerror=null;this.src='https://placehold.co/600x300/ab183d/ffffff?text=Pro+CSC+Tools';};});}
  function card(p){var btn=p.live?'<a href="'+p.url+'" class="read-more">Read Full Article <i class="fas fa-arrow-right"></i></a>':'<span class="text-xs font-semibold text-gray-400">Coming soon</span>';var link=p.live?p.url:'#';return '<article class="blog-card bg-white rounded-2xl shadow-md hover:shadow-xl border border-gray-100 flex flex-col overflow-hidden"><a href="'+link+'" class="block overflow-hidden h-44"><img src="'+p.img+'" alt="'+p.title+'" loading="lazy" data-fb class="thumb w-full h-44 object-cover"></a><div class="p-5 flex flex-col flex-grow"><span class="text-xs font-bold text-[#ab183d] uppercase tracking-wide">'+p.tag+'</span><h3 class="text-base font-bold text-gray-900 mt-2 mb-2 leading-snug">'+p.title+'</h3><p class="text-sm text-gray-600 flex-grow">'+p.excerpt+'</p><div class="flex items-center justify-between mt-4 pt-3 border-t border-gray-100"><span class="text-xs text-gray-400"><i class="far fa-calendar"></i> '+p.date+'</span>'+btn+'</div></div></article>';}
  function featuredCard(p){var btn=p.live?'<a href="'+p.url+'" class="inline-flex items-center gap-2 mt-4 bg-[#ab183d] text-white px-5 py-2.5 rounded-full font-semibold hover:bg-red-700 transition w-max">Read Full Article <i class="fas fa-arrow-right"></i></a>':'<span class="text-xs font-semibold text-gray-400 mt-4">Coming soon</span>';var link=p.live?p.url:'#';return '<div class="blog-card grid md:grid-cols-2 bg-white rounded-2xl shadow-md hover:shadow-xl border border-gray-100 overflow-hidden mb-8"><a href="'+link+'" class="block overflow-hidden h-56 md:h-auto"><img src="'+p.img+'" alt="'+p.title+'" data-fb class="thumb w-full h-full object-cover"></a><div class="p-6 flex flex-col justify-center"><span class="inline-flex items-center gap-1 text-xs font-bold text-white bg-[#ab183d] px-2.5 py-1 rounded-full w-max mb-3"><i class="fas fa-star"></i> FEATURED</span><h2 class="text-2xl font-extrabold text-gray-900 leading-snug">'+p.title+'</h2><p class="text-gray-600 mt-3">'+p.excerpt+'</p><span class="text-xs text-gray-400 mt-3"><i class="far fa-calendar"></i> '+p.date+' &middot; '+p.tag+'</span>'+btn+'</div></div>';}
  function render(){var list=blogPosts.filter(function(p){var okc=(active==='All'||p.tag===active);var okq=(!query||p.title.toLowerCase().indexOf(query)>-1||p.excerpt.toLowerCase().indexOf(query)>-1);return okc&&okq;});var showFeatured=(active==='All'&&!query&&list.length>0);if(featured)featured.innerHTML=showFeatured?featuredCard(list[0]):'';var rest=showFeatured?list.slice(1):list;grid.innerHTML=rest.map(card).join('');if(empty)empty.classList.toggle('hidden',list.length>0);fb();}
  if(catWrap){catWrap.innerHTML=cats.map(function(c){return '<button data-cat="'+c+'" class="cat-pill px-4 py-1.5 rounded-full text-sm font-semibold transition">'+c+'</button>';}).join('');catWrap.querySelectorAll('[data-cat]').forEach(function(btn){btn.addEventListener('click',function(){active=btn.getAttribute('data-cat');catWrap.querySelectorAll('[data-cat]').forEach(function(b){b.classList.remove('cat-active');});btn.classList.add('cat-active');render();});});var f=catWrap.querySelector('[data-cat]');if(f)f.classList.add('cat-active');}
  var s=document.getElementById('blogSearch');if(s){s.addEventListener('input',function(){query=s.value.toLowerCase().trim();render();});}
  render();
}
blogInit();
